reviews:
  namespace: gun-bookinfo-uat
  image: ghcr.io/gun082544/bookinfo-reviews
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  healthCheckPath: "/health"
ingress:
  host: bookinfo.uat.hellodolphin.in.th
  path: "/gun/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2