reviews:
  namespace: gun-bookinfo-uat
  image: ghcr.io/gun082544/bookinfo-reviews
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.uat.hellodolphin.in.th
  path: "/gun/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  RATINGS_SERVICE: http://ratings:8081
  ENABLE_RATINGS: true
  SERVICE_VERSION: v1
  STAR_COLOR: red